version: '3.9'

services:
    
    # TODO: Rename sdlc-rrdc to your application name (eg: my-app)
    docker-react:
        container_name: sdlc-rrdc
        build: 
            context: .
            dockerfile: Dockerfile
        volumes:
            - '.:/app'
            - '/app/node_modules'
        ports:
            - 3001:3000
        environment:
        - CHOKIDAR_USEPOLLING=true